name: cameraly
description: A comprehensive Flutter camera package with advanced features including orientation handling, metadata capture, custom UI, and smart permissions.
version: 1.0.1
homepage: https://github.com/yourusername/cameraly
repository: https://github.com/yourusername/cameraly
issue_tracker: https://github.com/yourusername/cameraly/issues
documentation: https://github.com/yourusername/cameraly/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Camera functionality
  camera: ^0.11.0
  
  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Permissions
  permission_handler: ^12.0.0+1
  
  # Device info and sensors
  device_info_plus: ^11.1.1
  sensors_plus: ^6.1.1
  
  # File system
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # Image processing and EXIF data
  image: ^4.0.17
  
  # JSON serialization
  json_annotation: ^4.9.0
  
  # Video playback (for thumbnails)
  video_player: ^2.9.5
  
  # Location services
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

# Package metadata
platforms:
  android:
  ios:

topics:
  - camera
  - photo
  - video
  - media
  - capture