name: cameraly
description: "A Flutter package that provides an enhanced camera experience with a developer-friendly API, building on top of the official Flutter camera plugin."
version: 0.1.0
homepage: https://github.com/InspectlyMads/cameraly
repository: https://github.com/InspectlyMads/cameraly
issue_tracker: https://github.com/InspectlyMads/cameraly/issues

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  camera_android: ^0.10.8+16
  camera_avfoundation: ^0.9.13+10
  camera_platform_interface: ^2.7.0
  path_provider: ^2.1.2
  path: ^1.8.3
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6
  meta: ^1.10.0
  cross_file: ^0.3.3+8
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true 