name: cameraly
description: A powerful and flexible camera package for Flutter that enhances the official camera plugin with a developer-friendly API, advanced features, and better error handling. Includes customizable overlays, media management, and comprehensive examples.
version: 0.1.0
homepage: https://github.com/InspectlyMads/cameraly
repository: https://github.com/InspectlyMads/cameraly
issue_tracker: https://github.com/InspectlyMads/cameraly/issues
documentation: https://github.com/InspectlyMads/cameraly/wiki
topics:
  - camera
  - photography
  - video
  - media
  - ui

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  path_provider: ^2.1.2
  path: ^1.8.3
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6
  cross_file: ^0.3.3+8
  image_picker: ^1.0.7
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2
  flutter_image_compress: ^2.1.0
  geolocator: ^13.0.3
  native_exif: ^0.6.0
  exif: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true 